export const API_CONSTANTS = {
    login: 'Auth/Login',
    zoneList: 'Zone?pageNo={pageNo}&pageSize={pageSize}',
    addZone : 'Zone',
    stateList: 'Common/GetStateList',
    updateZone: 'Zone/{zoneId}',
    circle: 'Circle?pageNo={pageNo}&pageSize={pageSize}',
    addCircle: 'Circle',
    deleteUpdateCircle: 'Circle/{circleId}',
    department: 'Common/GetDepartmentList',
    stateBasedZone: 'Common/GetZoneList?stateId={stateId}',
    zoneBasedCircle: 'Common/GetCircleList?zoneId={zoneId}',
    circleBasedcity: 'Common/GetDistrictList?circleId={circleId}',
    cityBasedDivision: 'Common/GetDivisionList?districtId={cityId}',
    designation: 'Common/GetDesignationList',
    usertype: 'Common/GetUserTypeList',
    district: 'District?pageNo={pageNo}&pageSize={pageSize}',
    addDistrict: 'District',
    updateDeleteDist: 'District/{distId}',
    user: 'User?pageNo={pageNo}&pageSize={pageSize}&searchText={searchText}',
    adduser: 'User',
    chiefEngList: "Common/GetChiefEngList",
    sEngList: 'Common/GetSupritendingEngList?chiefEngId={chiefEngId}',
    eeList: "Common/GetExecutiveEngList?supEngId={supEngId}",
    aeList: "Common/GetAssistantEngList?execEngId={execEngId}",
    jeList: "Common/GetJuniorEngList?assEngId={assEngId}",
    getDivisionDetails : 'Division?pageNo={pageNo}&pageSize={pageSize}',
    createDivision : 'Division',
    updateDivision : 'Division/{divisionId}',
    getZoneByChiefEng :'Common/GetZoneByChiefEng?chiefEngId={chiefEngId}',
    GetCircleBySupEng :'Common/GetCircleBySupEng?supEngId={supEngId}',
    GetDistrictByExecEng :'Common/GetDistrictByExecEng?execEngId={execEngId}',
    GetDivisionByAssEng :'Common/GetDivisionByAssEng?assEngId={assEngId}',
    userById : 'User/{userId}',
    category : 'Category?pageNo={pageNo}&pageSize={pageSize}',
    addcategory : 'Category',
    updateDelgetCat : "Category/{id}",
    SubCategory : "SubCategory?pageNo={pageNo}&pageSize={pageSize}&searchText={searchText}",
    addSubcategory : 'SubCategory',
    updateDelgetSubCat : "SubCategory/{id}",
    departmentData : 'Department?pageNo={pageNo}&pageSize={pageSize}',
    createDepartment : 'Department',
    getUpdateDeleteDepartment : 'Department/{id}',
    desigantion : 'Designation?pageNo={pageNo}&pageSize={pageSize}',
    createDesigantion : 'Designation',
    getUpdateDeleteDes : 'Designation/{id}',
    workList : 'Work?pageNo={pageNo}&pageSize={pageSize}',
    addWork : 'Work',
    getUpdateDeleteWork : 'Work/{id}',
    natureWorkList: 'Common/GetNatureOfWorkList',
    areaList : 'Area?pageNo={pageNo}&pageSize={pageSize}',
    addArea : 'Area',
    getDeletUpdateArea : 'Area/{id}',
    travelMode : 'Common/GetTravelModeList',
    POIAllocation : 'POIAllocation?pageNo={pageNo}&pageSize={pageSize}',
    addPOIAllocation : 'POIAllocation',
    getUpdateDeleteAllocation : 'POIAllocation/{id}',
    GetUserByDesig :'Common/GetUserByDesig?selectedDesig={id}',
    formCodeList : 'Common/GetFormCodeList',
    dashboardCount : 'Dashboard',
    districtReport : 'Report?pageNo={pageNo}&pageSize={pageSize}&zoneId={zoneId}&circleId={circleId}&districtId={districtId}',
    userDetails : 'Dashboard/GetUserDetailsWithLoc?userId={userId}&userDesigId={desiId}&locId={locId}',
    liveTracking : 'LiveTracking?selectedDesigId={selectedDesigId}&zoneId={zoneId}&circleId={circleId}&districtId={districtId}',
    poiArea : 'Common/GetAreaList',
    workAreaList :'Dashboard/GetWorkAreaListByUser?userId={userId}&workId={workId}',
    categoryListByArea: 'Dashboard/GetCategoryListByArea?taskId={taskId}',
    subCategoryListByCat: 'Dashboard/GetSubCategoryListByCat?taskId={taskId}&categoryId={categoryId}',
    commonArea : 'Common/GetAreaList',
    workListByUser : 'Dashboard/GetWorkListByUser?userId={userId}&userDesigId={userDesigId}',
    taskData : 'Task/GetImagesBasedOnCatSubCat?taskDetId={taskDetId}&catId={catId}&subCatId={subCatId}',
    addressApi : 'https://api.olamaps.io/places/v1/reverse-geocode?latlng={lat}%2C{lng}&api_key={api_key}',
    form1Data: 'Task/GetForm01?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form2Data: 'Task/GetForm02?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form3Data: 'Task/GetForm03?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form4Data: 'Task/GetForm04?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form5Data: 'Task/GetForm05?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form6Data: 'Task/GetForm06?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form7Data: 'Task/GetForm07?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form8Data: 'Task/GetForm08?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form9Data: 'Task/GetForm09?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form10Data: 'Task/GetForm10?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form11Data: 'Task/GetForm11?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form12Data: 'Task/GetForm12?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form13Data: 'Task/GetForm13?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form14Data: 'Task/GetForm14?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form15Data: 'Task/GetForm15?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form16Data: 'Task/GetForm16?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form17Data: 'Task/GetForm17?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form18Data: 'Task/GetForm18?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form19Data: 'Task/GetForm19?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form20Data: 'Task/GetForm20?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form21Data: 'Task/GetForm21?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form22Data: 'Task/GetForm22?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form23Data: 'Task/GetForm23?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form24Data: 'Task/GetForm24?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    form25Data: 'Task/GetForm25?taskId={taskId}&catId={catId}&subCatId={subCatId}',
    commonWork : 'Common/GetWorkList',
    liveTrackByUser : 'LiveTracking/GetLiveTrackingByUser?userId={userId}&selectedDesigId={selectedDesigId}'

}