export const API_CONSTANTS = {
    login: 'Auth/Login',
    zoneList: 'Zone?pageNo={pageNo}&pageSize={pageSize}',
    addZone : 'Zone',
    stateList: 'Common/GetStateList',
    updateZone: 'Zone/{zoneId}',
    circle: 'Circle?pageNo={pageNo}&pageSize={pageSize}',
    addCircle: 'Circle',
    deleteUpdateCircle: 'Circle/{circleId}',
    department: 'Common/GetDepartmentList',
    stateBasedZone: 'Common/GetZoneList?stateId={stateId}',
    zoneBasedCircle: 'Common/GetCircleList?zoneId={zoneId}',
    circleBasedcity: 'Common/GetDistrictList?circleId={circleId}',
    cityBasedDivision: 'Common/GetDivisionList?districtId={cityId}',
    designation: 'Common/GetDesignationList',
    usertype: 'Common/GetUserTypeList',
    district: 'District?pageNo={pageNo}&pageSize={pageSize}',
    addDistrict: 'District',
    updateDeleteDist: 'District/{distId}',
    user: 'User?pageNo={pageNo}&pageSize={pageSize}&searchText={searchText}',
    adduser: 'User',
    chiefEngList: "Common/GetChiefEngList",
    sEngList: 'Common/GetSupritendingEngList?chiefEngId={chiefEngId}',
    eeList: "Common/GetExecutiveEngList?supEngId={supEngId}",
    aeList: "Common/GetAssistantEngList?execEngId={execEngId}",
    jeList: "Common/GetJuniorEngList?assEngId={assEngId}",
    getDivisionDetails : 'Division?pageNo={pageNo}&pageSize={pageSize}',
    createDivision : 'Division',
    updateDivision : 'Division/{divisionId}',
    getZoneByChiefEng :'Common/GetZoneByChiefEng?chiefEngId={chiefEngId}',
    GetCircleBySupEng :'Common/GetCircleBySupEng?supEngId={supEngId}',
    GetDistrictByExecEng :'Common/GetDistrictByExecEng?execEngId={execEngId}',
    GetDivisionByAssEng :'Common/GetDivisionByAssEng?assEngId={assEngId}',
    userById : 'User/{userId}',
    category : 'Category?pageNo={pageNo}&pageSize={pageSize}',
    addcategory : 'Category',
    updateDelgetCat : "Category/{id}",
    SubCategory : "SubCategory?pageNo={pageNo}&pageSize={pageSize}",
    addSubcategory : 'SubCategory',
    updateDelgetSubCat : "SubCategory/{id}",
    departmentData : 'Department?pageNo={pageNo}&pageSize={pageSize}',
    createDepartment : 'Department',
    getUpdateDeleteDepartment : 'Department/{id}',
    desigantion : 'Designation?pageNo={pageNo}&pageSize={pageSize}',
    createDesigantion : 'Designation',
    getUpdateDeleteDes : 'Designation/{id}',
    workList : 'Work?pageNo={pageNo}&pageSize={pageSize}',
    addWork : 'Work',
    getUpdateDeleteWork : 'Work/{id}',
    natureWorkList: 'Common/GetNatureOfWorkList',
    areaList : 'Area?pageNo={pageNo}&pageSize={pageSize}',
    addArea : 'Area',
    getDeletUpdateArea : 'Area/{id}',
    travelMode : 'Common/GetTravelModeList',
    POIAllocation : 'POIAllocation?pageNo={pageNo}&pageSize={pageSize}',
    addPOIAllocation : 'POIAllocation',
    getUpdateDeleteAllocation : 'POIAllocation/{id}',
    GetUserByDesig :'Common/GetUserByDesig?selectedDesig={id}',
    formCodeList : 'Common/GetFormCodeList',
    dashboardCount : 'Dashboard',
    districtReport : 'Report?pageNo={pageNo}&pageSize={pageSize}&zoneId={zoneId}&circleId={circleId}&districtId={districtId}',
    userDetails : 'Dashboard/GetUserDetailsWithLoc?userId={userId}&userDesigId={desiId}&locId={locId}',
    liveTracking : 'LiveTracking?selectedDesigId={selectedDesigId}&zoneId={zoneId}&circleId={circleId}&districtId={districtId}',
    poiArea : 'Common/GetAreaList',
    workAreaList :'Dashboard/GetWorkAreaListByUser?userId={userId}&userDesigId={userDesigId}',
    categoryListByArea: 'Dashboard/GetCategoryListByArea?taskId={taskId}',
    subCategoryListByCat: 'Dashboard/GetSubCategoryListByCat?taskId={taskId}&categoryId={categoryId}'
}